2015-03-08 22:05:34.247 15315 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.493 8278 INFO neutron.wsgi [-] (8278) accepted ('13.0.0.3', 52904)
2015-03-09 22:05:24.495 8278 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.533 8266 INFO neutron.wsgi [-] (8266) accepted ('13.0.0.3', 52914)
2015-03-09 22:05:24.536 8266 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.561 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52920)
2015-03-09 22:05:24.562 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52922)
2015-03-09 22:05:24.564 8278 INFO neutron.quota [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45ca8d0>.
2015-03-09 22:05:24.565 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.565 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.567 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52928)
2015-03-09 22:05:24.570 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52930)
2015-03-09 22:05:24.570 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.572 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.592 8278 INFO neutron.plugins.ml2.db [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Added segment df12bce5-f650-4818-80d9-180855d3a6ed of type vlan for network 0ae1d5c6-68d6-496a-ba51-0d664ed70552
2015-03-09 22:05:24.602 8266 INFO neutron.quota [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x519f5d0>.
2015-03-09 22:05:24.604 8278 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.622 8266 INFO neutron.plugins.ml2.db [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Added segment 37633bc7-68a2-4750-a811-eede45ca425b of type vlan for network 7967ad50-6c6b-4c34-b7ca-49dff418ea33
2015-03-09 22:05:24.624 8275 INFO neutron.wsgi [-] (8275) accepted ('13.0.0.3', 52937)
2015-03-09 22:05:24.627 8275 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.632 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.633 8266 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.633 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.650 8276 INFO neutron.quota [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4a72290>.
2015-03-09 22:05:24.650 8271 INFO neutron.quota [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x51ab5d0>.
2015-03-09 22:05:24.652 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.668 8276 INFO neutron.plugins.ml2.db [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Added segment 8765e24b-8d98-4888-a183-7f8ad603d701 of type vlan for network c8042ac8-8810-4482-82c3-69dc14cdd0e7
2015-03-09 22:05:24.679 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.686 8275 INFO neutron.quota [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x5137990>.
2015-03-09 22:05:24.695 8271 ERROR neutron.api.v2.resource [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] create failed
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.697 8271 INFO neutron.wsgi [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.133756
2015-03-09 22:05:24.697 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.697 8276 INFO neutron.plugins.ml2.db [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd None] Added segment 1be100a1-6f2a-4b4e-9543-1c6681a55946 of type vlan for network 11ce70d7-60e8-4ee6-825a-0bc5eb20a09a
2015-03-09 22:05:24.707 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.720 8271 INFO neutron.plugins.ml2.db [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c None] Added segment 03c2f9d8-e027-49a5-abd0-696a19f70559 of type vlan for network c79ae256-b6f4-441e-ae65-cb1546575e15
2015-03-09 22:05:24.724 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52946)
2015-03-09 22:05:24.723 8275 ERROR neutron.api.v2.resource [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] create failed
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.725 8275 INFO neutron.wsgi [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.099801
2015-03-09 22:05:24.730 8271 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.737 8272 INFO neutron.wsgi [-] (8272) accepted ('13.0.0.3', 52949)
2015-03-09 22:05:24.738 8267 INFO neutron.wsgi [-] (8267) accepted ('13.0.0.3', 52951)
2015-03-09 22:05:24.740 8272 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.740 8267 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-08 22:05:34.247 15315 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.493 8278 INFO neutron.wsgi [-] (8278) accepted ('13.0.0.3', 52904)
2015-03-09 22:05:24.495 8278 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.533 8266 INFO neutron.wsgi [-] (8266) accepted ('13.0.0.3', 52914)
2015-03-09 22:05:24.536 8266 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.561 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52920)
2015-03-09 22:05:24.562 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52922)
2015-03-09 22:05:24.564 8278 INFO neutron.quota [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45ca8d0>.
2015-03-09 22:05:24.565 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.565 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.567 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52928)
2015-03-09 22:05:24.570 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52930)
2015-03-09 22:05:24.570 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.572 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.592 8278 INFO neutron.plugins.ml2.db [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Added segment df12bce5-f650-4818-80d9-180855d3a6ed of type vlan for network 0ae1d5c6-68d6-496a-ba51-0d664ed70552
2015-03-09 22:05:24.602 8266 INFO neutron.quota [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x519f5d0>.
2015-03-09 22:05:24.604 8278 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.622 8266 INFO neutron.plugins.ml2.db [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Added segment 37633bc7-68a2-4750-a811-eede45ca425b of type vlan for network 7967ad50-6c6b-4c34-b7ca-49dff418ea33
2015-03-09 22:05:24.624 8275 INFO neutron.wsgi [-] (8275) accepted ('13.0.0.3', 52937)
2015-03-09 22:05:24.627 8275 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.632 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.633 8266 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.633 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.650 8276 INFO neutron.quota [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4a72290>.
2015-03-09 22:05:24.650 8271 INFO neutron.quota [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x51ab5d0>.
2015-03-09 22:05:24.652 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.668 8276 INFO neutron.plugins.ml2.db [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Added segment 8765e24b-8d98-4888-a183-7f8ad603d701 of type vlan for network c8042ac8-8810-4482-82c3-69dc14cdd0e7
2015-03-09 22:05:24.679 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.686 8275 INFO neutron.quota [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x5137990>.
2015-03-09 22:05:24.695 8271 ERROR neutron.api.v2.resource [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] create failed
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.697 8271 INFO neutron.wsgi [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.133756
2015-03-09 22:05:24.697 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.697 8276 INFO neutron.plugins.ml2.db [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd None] Added segment 1be100a1-6f2a-4b4e-9543-1c6681a55946 of type vlan for network 11ce70d7-60e8-4ee6-825a-0bc5eb20a09a
2015-03-09 22:05:24.707 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.720 8271 INFO neutron.plugins.ml2.db [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c None] Added segment 03c2f9d8-e027-49a5-abd0-696a19f70559 of type vlan for network c79ae256-b6f4-441e-ae65-cb1546575e15
2015-03-09 22:05:24.724 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52946)
2015-03-09 22:05:24.723 8275 ERROR neutron.api.v2.resource [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] create failed
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.725 8275 INFO neutron.wsgi [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.099801
2015-03-09 22:05:24.730 8271 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.737 8272 INFO neutron.wsgi [-] (8272) accepted ('13.0.0.3', 52949)
2015-03-09 22:05:24.738 8267 INFO neutron.wsgi [-] (8267) accepted ('13.0.0.3', 52951)
2015-03-09 22:05:24.740 8272 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.740 8267 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.770 8276 INFO neutron.plugins.ml2.db [req-97375109-87fd-440c-bbbc-cd74a56bfd0a None] Added segment 07711728-5fef-4853-90cf-0fec50b43967 of type vlan for network 05020391-8453-4843-acf0-b8481abe4e0a
2015-03-08 22:05:34.247 15315 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.493 8278 INFO neutron.wsgi [-] (8278) accepted ('13.0.0.3', 52904)
2015-03-09 22:05:24.495 8278 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.533 8266 INFO neutron.wsgi [-] (8266) accepted ('13.0.0.3', 52914)
2015-03-09 22:05:24.536 8266 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.561 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52920)
2015-03-09 22:05:24.562 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52922)
2015-03-09 22:05:24.564 8278 INFO neutron.quota [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45ca8d0>.
2015-03-09 22:05:24.565 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.565 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.567 8271 INFO neutron.wsgi [-] (8271) accepted ('13.0.0.3', 52928)
2015-03-09 22:05:24.570 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52930)
2015-03-09 22:05:24.570 8271 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.572 8276 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.592 8278 INFO neutron.plugins.ml2.db [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Added segment df12bce5-f650-4818-80d9-180855d3a6ed of type vlan for network 0ae1d5c6-68d6-496a-ba51-0d664ed70552
2015-03-09 22:05:24.602 8266 INFO neutron.quota [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x519f5d0>.
2015-03-09 22:05:24.604 8278 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.622 8266 INFO neutron.plugins.ml2.db [req-bc8fa50f-e06a-46c9-98b1-fb96ba47f4c8 None] Added segment 37633bc7-68a2-4750-a811-eede45ca425b of type vlan for network 7967ad50-6c6b-4c34-b7ca-49dff418ea33
2015-03-09 22:05:24.624 8275 INFO neutron.wsgi [-] (8275) accepted ('13.0.0.3', 52937)
2015-03-09 22:05:24.627 8275 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.632 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.633 8266 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.633 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.650 8276 INFO neutron.quota [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4a72290>.
2015-03-09 22:05:24.650 8271 INFO neutron.quota [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x51ab5d0>.
2015-03-09 22:05:24.652 8276 INFO oslo.messaging._drivers.impl_rabbit [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.668 8276 INFO neutron.plugins.ml2.db [req-a02f60bd-d912-4687-83c5-335d82cdd73c None] Added segment 8765e24b-8d98-4888-a183-7f8ad603d701 of type vlan for network c8042ac8-8810-4482-82c3-69dc14cdd0e7
2015-03-09 22:05:24.679 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.686 8275 INFO neutron.quota [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x5137990>.
2015-03-09 22:05:24.695 8271 ERROR neutron.api.v2.resource [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] create failed
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.695 8271 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.697 8271 INFO neutron.wsgi [req-d16f2859-68a5-4ad8-b036-a66603efbb31 None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.133756
2015-03-09 22:05:24.697 8271 INFO oslo.messaging._drivers.impl_rabbit [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c ] Connected to AMQP server on 13.0.0.3:5672
2015-03-09 22:05:24.697 8276 INFO neutron.plugins.ml2.db [req-72470d23-9aaa-45a6-8b6f-7597fd125bfd None] Added segment 1be100a1-6f2a-4b4e-9543-1c6681a55946 of type vlan for network 11ce70d7-60e8-4ee6-825a-0bc5eb20a09a
2015-03-09 22:05:24.707 8276 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.720 8271 INFO neutron.plugins.ml2.db [req-e3417067-70fd-49a0-89a8-c044a5b4ca0c None] Added segment 03c2f9d8-e027-49a5-abd0-696a19f70559 of type vlan for network c79ae256-b6f4-441e-ae65-cb1546575e15
2015-03-09 22:05:24.724 8276 INFO neutron.wsgi [-] (8276) accepted ('13.0.0.3', 52946)
2015-03-09 22:05:24.723 8275 ERROR neutron.api.v2.resource [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] create failed
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.723 8275 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.725 8275 INFO neutron.wsgi [req-fac1ae5a-1e0f-41f0-8834-e598e75e5dff None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.099801
2015-03-09 22:05:24.730 8271 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.737 8272 INFO neutron.wsgi [-] (8272) accepted ('13.0.0.3', 52949)
2015-03-09 22:05:24.738 8267 INFO neutron.wsgi [-] (8267) accepted ('13.0.0.3', 52951)
2015-03-09 22:05:24.740 8272 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.740 8267 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 22:05:24.770 8276 INFO neutron.plugins.ml2.db [req-97375109-87fd-440c-bbbc-cd74a56bfd0a None] Added segment 07711728-5fef-4853-90cf-0fec50b43967 of type vlan for network 05020391-8453-4843-acf0-b8481abe4e0a
2015-03-09 22:05:24.803 8267 INFO neutron.quota [req-f36c22d3-f58e-4e9d-848a-11a7929ea42d None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4cc1810>.
2015-03-09 22:05:24.806 8272 INFO neutron.quota [req-3e548862-4fcc-4998-b250-125deea1c76a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4f87590>.
2015-03-09 22:05:24.823 8267 INFO neutron.plugins.ml2.db [req-f36c22d3-f58e-4e9d-848a-11a7929ea42d None] Added segment ce14fbcf-118e-4d3a-8d46-cf23648ac2ce of type vlan for network 46c32b8c-3795-4424-95dc-c644fe5e9792
2015-03-09 22:05:24.929 8267 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 22:05:24.949 8272 ERROR neutron.api.v2.resource [req-3e548862-4fcc-4998-b250-125deea1c76a None] create failed
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     tenant_id)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-09 22:05:24.949 8272 TRACE neutron.api.v2.resource 
2015-03-09 22:05:24.951 8272 INFO neutron.wsgi [req-3e548862-4fcc-4998-b250-125deea1c76a None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.212849
2015-03-09 22:05:24.989 8278 INFO neutron.plugins.ml2.drivers.cisco.n1kv.n1kv_client [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] VSM: Successfully modified "network-segment 0ae1d5c6-68d6-496a-ba51-0d664ed70552"
2015-03-09 22:05:24.989 8278 INFO neutron.plugins.ml2.drivers.cisco.n1kv.mech_cisco_n1kv [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] Create network(postcommit) succeeded for network: 0ae1d5c6-68d6-496a-ba51-0d664ed70552 of type: vlan with segment id: 100
2015-03-09 22:05:24.994 8278 INFO neutron.wsgi [req-f49cf8c0-00bc-4585-80aa-12f612eefb51 None] 13.0.0.3 - - [09/Mar/2015 22:05:24] "POST /v2.0/networks.json HTTP/1.1" 201 426 0.500353
