2015-03-09 03:15:18.908 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40889)
2015-03-09 03:15:18.910 15289 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 03:15:18.982 15289 INFO neutron.plugins.ml2.managers [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:18.984 15289 INFO neutron.wsgi [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] 13.0.0.3 - - [09/Mar/2015 03:15:18] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=bddb85f8-150a-4252-84c9-05b2918899c5 HTTP/1.1" 200 996 0.074996
2015-03-09 03:15:18.987 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40895)
2015-03-09 03:15:18.997 15289 INFO neutron.plugins.ml2.managers [req-8d47e404-7957-4839-9c72-a340d61ce569 None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.000 15289 INFO neutron.wsgi [req-8d47e404-7957-4839-9c72-a340d61ce569 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/networks.json?id=619b3cb6-c5bb-469b-8525-44a53fc87630 HTTP/1.1" 200 578 0.012433
2015-03-09 03:15:19.002 15303 INFO neutron.wsgi [-] (15303) accepted ('13.0.0.3', 40896)
2015-03-09 03:15:19.009 15303 INFO neutron.wsgi [req-a6f0586e-a8fb-4c11-a149-c5555b85b384 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.9.2&port_id=ce179fb2-6014-4f8e-acaa-6a1dd23d8887 HTTP/1.1" 200 208 0.005573
2015-03-09 03:15:19.011 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40897)
2015-03-09 03:15:19.021 15289 INFO neutron.plugins.ml2.managers [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.021 15289 INFO neutron.wsgi [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/subnets.json?id=cf17974a-345d-40f1-8fa6-87fff881e1fe HTTP/1.1" 200 623 0.009591
2015-03-09 03:15:19.024 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40898)
2015-03-09 03:15:19.041 15289 INFO neutron.plugins.ml2.managers [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.042 15289 INFO neutron.wsgi [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/ports.json?network_id=619b3cb6-c5bb-469b-8525-44a53fc87630&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.017388
2015-03-09 03:15:38.698 15273 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:54.176 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41490)
2015-03-09 03:15:54.194 15289 INFO neutron.plugins.ml2.managers [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.196 15289 INFO neutron.wsgi [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=8bc3989e-8836-4cdb-8fff-0ce279933da4 HTTP/1.1" 200 996 0.018769
2015-03-09 03:15:54.198 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41491)
2015-03-09 03:15:54.210 15289 INFO neutron.plugins.ml2.managers [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.213 15289 INFO neutron.wsgi [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/networks.json?id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4 HTTP/1.1" 200 577 0.014159
2015-03-09 03:15:54.215 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41492)
2015-03-09 03:15:54.220 15289 INFO neutron.wsgi [req-b0221032-e7d4-45e7-894f-54e8b3bd75db None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.2.2&port_id=8640b9eb-affb-47ce-84fb-32c2d4ce1baf HTTP/1.1" 200 208 0.004424
2015-03-09 03:15:54.222 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41493)
2015-03-09 03:15:54.233 15289 INFO neutron.plugins.ml2.managers [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.234 15289 INFO neutron.wsgi [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/subnets.json?id=1e6eeaf3-d276-4384-b6d7-73c2f65446b5 HTTP/1.1" 200 622 0.010641
2015-03-09 03:15:54.236 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41494)
2015-03-09 03:15:54.252 15289 INFO neutron.plugins.ml2.managers [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.253 15289 INFO neutron.wsgi [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?network_id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.016796
2015-03-10 03:15:30.584 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57238)
2015-03-10 03:15:30.588 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.664 27053 INFO neutron.wsgi [-] (27053) accepted ('13.0.0.3', 57248)
2015-03-10 03:15:30.669 27053 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.702 27057 INFO neutron.wsgi [-] (27057) accepted ('13.0.0.3', 57254)
2015-03-10 03:15:30.708 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.709 27060 INFO neutron.wsgi [-] (27060) accepted ('13.0.0.3', 57257)
2015-03-10 03:15:30.713 27060 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.751 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57266)
2015-03-10 03:15:30.756 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.759 27058 INFO keystonemiddleware.auth_token [-] Auth Token confirmed use of v3.0 apis
2015-03-10 03:15:30.768 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57270)
2015-03-10 03:15:30.773 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.777 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57274)
2015-03-10 03:15:30.779 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.892 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.901 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.910 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.912 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.919 27059 INFO neutron.wsgi [-] (27059) accepted ('13.0.0.3', 57286)
2015-03-10 03:15:30.924 27049 INFO neutron.wsgi [-] (27049) accepted ('13.0.0.3', 57288)
2015-03-10 03:15:30.929 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.933 27055 INFO neutron.wsgi [-] (27055) accepted ('13.0.0.3', 57290)
2015-03-10 03:15:30.947 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.958 27058 INFO neutron.quota [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4566a90>.
2015-03-10 03:15:30.967 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.969 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.976 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.978 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.994 27058 INFO neutron.plugins.ml2.db [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Added segment 01ae8df2-465b-4d54-9920-fa41a8caa930 of type vlan for network 64063da1-4a72-4609-85e7-1e942922c85f
2015-03-10 03:15:31.009 27053 INFO neutron.quota [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dce10>.
2015-03-10 03:15:31.015 27057 INFO neutron.quota [req-12862fe0-0f87-4024-8541-8875a015e943 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.017 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.018 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.019 27060 INFO neutron.quota [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.021 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.026 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.030 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.036 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.037 27057 INFO neutron.plugins.ml2.db [req-12862fe0-0f87-4024-8541-8875a015e943 None] Added segment 5df1e09c-afda-49ed-aed6-765789e0bf02 of type vlan for network 66dc694d-83c5-4c10-a688-7b317876407e
2015-03-10 03:15:31.048 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.048 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.063 27053 ERROR neutron.api.v2.resource [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] create failed
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.065 27049 INFO neutron.quota [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41dfe50>.
2015-03-10 03:15:31.066 27053 INFO neutron.wsgi [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401648
2015-03-10 03:15:31.068 27059 INFO neutron.quota [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.075 27055 INFO neutron.quota [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.086 27049 INFO neutron.plugins.ml2.db [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Added segment bbd59b56-df3e-4e2c-88ce-c03bf0e95222 of type vlan for network 8673537a-360e-4fb6-8af7-3b8c1a46f33a
2015-03-10 03:15:31.088 27058 ERROR neutron.api.v2.resource [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] create failed
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.091 27058 INFO neutron.wsgi [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.339519
2015-03-10 03:15:31.097 27049 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.099 27056 INFO neutron.quota [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x46f9a90>.
2015-03-10 03:15:31.109 27060 ERROR neutron.api.v2.resource [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] create failed
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.111 27060 INFO neutron.wsgi [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401427
2015-03-10 03:15:31.113 27059 ERROR neutron.api.v2.resource [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] create failed
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.115 27059 INFO neutron.wsgi [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.195798
2015-03-09 03:15:18.908 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40889)
2015-03-09 03:15:18.910 15289 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 03:15:18.982 15289 INFO neutron.plugins.ml2.managers [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:18.984 15289 INFO neutron.wsgi [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] 13.0.0.3 - - [09/Mar/2015 03:15:18] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=bddb85f8-150a-4252-84c9-05b2918899c5 HTTP/1.1" 200 996 0.074996
2015-03-09 03:15:18.987 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40895)
2015-03-09 03:15:18.997 15289 INFO neutron.plugins.ml2.managers [req-8d47e404-7957-4839-9c72-a340d61ce569 None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.000 15289 INFO neutron.wsgi [req-8d47e404-7957-4839-9c72-a340d61ce569 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/networks.json?id=619b3cb6-c5bb-469b-8525-44a53fc87630 HTTP/1.1" 200 578 0.012433
2015-03-09 03:15:19.002 15303 INFO neutron.wsgi [-] (15303) accepted ('13.0.0.3', 40896)
2015-03-09 03:15:19.009 15303 INFO neutron.wsgi [req-a6f0586e-a8fb-4c11-a149-c5555b85b384 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.9.2&port_id=ce179fb2-6014-4f8e-acaa-6a1dd23d8887 HTTP/1.1" 200 208 0.005573
2015-03-09 03:15:19.011 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40897)
2015-03-09 03:15:19.021 15289 INFO neutron.plugins.ml2.managers [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.021 15289 INFO neutron.wsgi [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/subnets.json?id=cf17974a-345d-40f1-8fa6-87fff881e1fe HTTP/1.1" 200 623 0.009591
2015-03-09 03:15:19.024 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40898)
2015-03-09 03:15:19.041 15289 INFO neutron.plugins.ml2.managers [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.042 15289 INFO neutron.wsgi [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/ports.json?network_id=619b3cb6-c5bb-469b-8525-44a53fc87630&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.017388
2015-03-09 03:15:38.698 15273 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:54.176 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41490)
2015-03-09 03:15:54.194 15289 INFO neutron.plugins.ml2.managers [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.196 15289 INFO neutron.wsgi [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=8bc3989e-8836-4cdb-8fff-0ce279933da4 HTTP/1.1" 200 996 0.018769
2015-03-09 03:15:54.198 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41491)
2015-03-09 03:15:54.210 15289 INFO neutron.plugins.ml2.managers [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.213 15289 INFO neutron.wsgi [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/networks.json?id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4 HTTP/1.1" 200 577 0.014159
2015-03-09 03:15:54.215 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41492)
2015-03-09 03:15:54.220 15289 INFO neutron.wsgi [req-b0221032-e7d4-45e7-894f-54e8b3bd75db None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.2.2&port_id=8640b9eb-affb-47ce-84fb-32c2d4ce1baf HTTP/1.1" 200 208 0.004424
2015-03-09 03:15:54.222 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41493)
2015-03-09 03:15:54.233 15289 INFO neutron.plugins.ml2.managers [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.234 15289 INFO neutron.wsgi [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/subnets.json?id=1e6eeaf3-d276-4384-b6d7-73c2f65446b5 HTTP/1.1" 200 622 0.010641
2015-03-09 03:15:54.236 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41494)
2015-03-09 03:15:54.252 15289 INFO neutron.plugins.ml2.managers [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.253 15289 INFO neutron.wsgi [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?network_id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.016796
2015-03-10 03:15:30.584 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57238)
2015-03-10 03:15:30.588 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.664 27053 INFO neutron.wsgi [-] (27053) accepted ('13.0.0.3', 57248)
2015-03-10 03:15:30.669 27053 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.702 27057 INFO neutron.wsgi [-] (27057) accepted ('13.0.0.3', 57254)
2015-03-10 03:15:30.708 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.709 27060 INFO neutron.wsgi [-] (27060) accepted ('13.0.0.3', 57257)
2015-03-10 03:15:30.713 27060 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.751 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57266)
2015-03-10 03:15:30.756 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.759 27058 INFO keystonemiddleware.auth_token [-] Auth Token confirmed use of v3.0 apis
2015-03-10 03:15:30.768 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57270)
2015-03-10 03:15:30.773 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.777 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57274)
2015-03-10 03:15:30.779 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.892 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.901 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.910 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.912 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.919 27059 INFO neutron.wsgi [-] (27059) accepted ('13.0.0.3', 57286)
2015-03-10 03:15:30.924 27049 INFO neutron.wsgi [-] (27049) accepted ('13.0.0.3', 57288)
2015-03-10 03:15:30.929 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.933 27055 INFO neutron.wsgi [-] (27055) accepted ('13.0.0.3', 57290)
2015-03-10 03:15:30.947 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.958 27058 INFO neutron.quota [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4566a90>.
2015-03-10 03:15:30.967 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.969 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.976 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.978 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.994 27058 INFO neutron.plugins.ml2.db [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Added segment 01ae8df2-465b-4d54-9920-fa41a8caa930 of type vlan for network 64063da1-4a72-4609-85e7-1e942922c85f
2015-03-10 03:15:31.009 27053 INFO neutron.quota [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dce10>.
2015-03-10 03:15:31.015 27057 INFO neutron.quota [req-12862fe0-0f87-4024-8541-8875a015e943 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.017 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.018 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.019 27060 INFO neutron.quota [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.021 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.026 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.030 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.036 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.037 27057 INFO neutron.plugins.ml2.db [req-12862fe0-0f87-4024-8541-8875a015e943 None] Added segment 5df1e09c-afda-49ed-aed6-765789e0bf02 of type vlan for network 66dc694d-83c5-4c10-a688-7b317876407e
2015-03-10 03:15:31.048 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.048 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.063 27053 ERROR neutron.api.v2.resource [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] create failed
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.065 27049 INFO neutron.quota [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41dfe50>.
2015-03-10 03:15:31.066 27053 INFO neutron.wsgi [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401648
2015-03-10 03:15:31.068 27059 INFO neutron.quota [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.075 27055 INFO neutron.quota [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.086 27049 INFO neutron.plugins.ml2.db [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Added segment bbd59b56-df3e-4e2c-88ce-c03bf0e95222 of type vlan for network 8673537a-360e-4fb6-8af7-3b8c1a46f33a
2015-03-10 03:15:31.088 27058 ERROR neutron.api.v2.resource [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] create failed
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.091 27058 INFO neutron.wsgi [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.339519
2015-03-10 03:15:31.097 27049 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.099 27056 INFO neutron.quota [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x46f9a90>.
2015-03-10 03:15:31.109 27060 ERROR neutron.api.v2.resource [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] create failed
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.111 27060 INFO neutron.wsgi [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401427
2015-03-10 03:15:31.113 27059 ERROR neutron.api.v2.resource [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] create failed
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.115 27059 INFO neutron.wsgi [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.195798
2015-03-10 03:15:31.124 27056 INFO neutron.plugins.ml2.db [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Added segment d6c88af2-d06c-444a-9bb1-37145c418d95 of type vlan for network 22c8b610-33e2-4910-b8a3-5f0e88dca049
2015-03-10 03:15:31.136 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.136 27055 ERROR neutron.api.v2.resource [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] create failed
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.138 27055 INFO neutron.wsgi [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.204934
2015-03-09 03:15:18.908 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40889)
2015-03-09 03:15:18.910 15289 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 03:15:18.982 15289 INFO neutron.plugins.ml2.managers [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:18.984 15289 INFO neutron.wsgi [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] 13.0.0.3 - - [09/Mar/2015 03:15:18] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=bddb85f8-150a-4252-84c9-05b2918899c5 HTTP/1.1" 200 996 0.074996
2015-03-09 03:15:18.987 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40895)
2015-03-09 03:15:18.997 15289 INFO neutron.plugins.ml2.managers [req-8d47e404-7957-4839-9c72-a340d61ce569 None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.000 15289 INFO neutron.wsgi [req-8d47e404-7957-4839-9c72-a340d61ce569 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/networks.json?id=619b3cb6-c5bb-469b-8525-44a53fc87630 HTTP/1.1" 200 578 0.012433
2015-03-09 03:15:19.002 15303 INFO neutron.wsgi [-] (15303) accepted ('13.0.0.3', 40896)
2015-03-09 03:15:19.009 15303 INFO neutron.wsgi [req-a6f0586e-a8fb-4c11-a149-c5555b85b384 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.9.2&port_id=ce179fb2-6014-4f8e-acaa-6a1dd23d8887 HTTP/1.1" 200 208 0.005573
2015-03-09 03:15:19.011 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40897)
2015-03-09 03:15:19.021 15289 INFO neutron.plugins.ml2.managers [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.021 15289 INFO neutron.wsgi [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/subnets.json?id=cf17974a-345d-40f1-8fa6-87fff881e1fe HTTP/1.1" 200 623 0.009591
2015-03-09 03:15:19.024 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40898)
2015-03-09 03:15:19.041 15289 INFO neutron.plugins.ml2.managers [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.042 15289 INFO neutron.wsgi [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/ports.json?network_id=619b3cb6-c5bb-469b-8525-44a53fc87630&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.017388
2015-03-09 03:15:38.698 15273 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:54.176 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41490)
2015-03-09 03:15:54.194 15289 INFO neutron.plugins.ml2.managers [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.196 15289 INFO neutron.wsgi [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=8bc3989e-8836-4cdb-8fff-0ce279933da4 HTTP/1.1" 200 996 0.018769
2015-03-09 03:15:54.198 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41491)
2015-03-09 03:15:54.210 15289 INFO neutron.plugins.ml2.managers [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.213 15289 INFO neutron.wsgi [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/networks.json?id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4 HTTP/1.1" 200 577 0.014159
2015-03-09 03:15:54.215 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41492)
2015-03-09 03:15:54.220 15289 INFO neutron.wsgi [req-b0221032-e7d4-45e7-894f-54e8b3bd75db None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.2.2&port_id=8640b9eb-affb-47ce-84fb-32c2d4ce1baf HTTP/1.1" 200 208 0.004424
2015-03-09 03:15:54.222 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41493)
2015-03-09 03:15:54.233 15289 INFO neutron.plugins.ml2.managers [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.234 15289 INFO neutron.wsgi [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/subnets.json?id=1e6eeaf3-d276-4384-b6d7-73c2f65446b5 HTTP/1.1" 200 622 0.010641
2015-03-09 03:15:54.236 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41494)
2015-03-09 03:15:54.252 15289 INFO neutron.plugins.ml2.managers [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.253 15289 INFO neutron.wsgi [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?network_id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.016796
2015-03-10 03:15:30.584 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57238)
2015-03-10 03:15:30.588 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.664 27053 INFO neutron.wsgi [-] (27053) accepted ('13.0.0.3', 57248)
2015-03-10 03:15:30.669 27053 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.702 27057 INFO neutron.wsgi [-] (27057) accepted ('13.0.0.3', 57254)
2015-03-10 03:15:30.708 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.709 27060 INFO neutron.wsgi [-] (27060) accepted ('13.0.0.3', 57257)
2015-03-10 03:15:30.713 27060 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.751 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57266)
2015-03-10 03:15:30.756 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.759 27058 INFO keystonemiddleware.auth_token [-] Auth Token confirmed use of v3.0 apis
2015-03-10 03:15:30.768 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57270)
2015-03-10 03:15:30.773 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.777 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57274)
2015-03-10 03:15:30.779 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.892 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.901 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.910 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.912 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.919 27059 INFO neutron.wsgi [-] (27059) accepted ('13.0.0.3', 57286)
2015-03-10 03:15:30.924 27049 INFO neutron.wsgi [-] (27049) accepted ('13.0.0.3', 57288)
2015-03-10 03:15:30.929 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.933 27055 INFO neutron.wsgi [-] (27055) accepted ('13.0.0.3', 57290)
2015-03-10 03:15:30.947 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.958 27058 INFO neutron.quota [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4566a90>.
2015-03-10 03:15:30.967 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.969 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.976 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.978 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.994 27058 INFO neutron.plugins.ml2.db [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Added segment 01ae8df2-465b-4d54-9920-fa41a8caa930 of type vlan for network 64063da1-4a72-4609-85e7-1e942922c85f
2015-03-10 03:15:31.009 27053 INFO neutron.quota [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dce10>.
2015-03-10 03:15:31.015 27057 INFO neutron.quota [req-12862fe0-0f87-4024-8541-8875a015e943 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.017 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.018 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.019 27060 INFO neutron.quota [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.021 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.026 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.030 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.036 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.037 27057 INFO neutron.plugins.ml2.db [req-12862fe0-0f87-4024-8541-8875a015e943 None] Added segment 5df1e09c-afda-49ed-aed6-765789e0bf02 of type vlan for network 66dc694d-83c5-4c10-a688-7b317876407e
2015-03-10 03:15:31.048 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.048 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.063 27053 ERROR neutron.api.v2.resource [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] create failed
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.065 27049 INFO neutron.quota [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41dfe50>.
2015-03-10 03:15:31.066 27053 INFO neutron.wsgi [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401648
2015-03-10 03:15:31.068 27059 INFO neutron.quota [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.075 27055 INFO neutron.quota [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.086 27049 INFO neutron.plugins.ml2.db [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Added segment bbd59b56-df3e-4e2c-88ce-c03bf0e95222 of type vlan for network 8673537a-360e-4fb6-8af7-3b8c1a46f33a
2015-03-10 03:15:31.088 27058 ERROR neutron.api.v2.resource [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] create failed
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.091 27058 INFO neutron.wsgi [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.339519
2015-03-10 03:15:31.097 27049 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.099 27056 INFO neutron.quota [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x46f9a90>.
2015-03-10 03:15:31.109 27060 ERROR neutron.api.v2.resource [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] create failed
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.111 27060 INFO neutron.wsgi [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401427
2015-03-10 03:15:31.113 27059 ERROR neutron.api.v2.resource [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] create failed
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.115 27059 INFO neutron.wsgi [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.195798
2015-03-10 03:15:31.124 27056 INFO neutron.plugins.ml2.db [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Added segment d6c88af2-d06c-444a-9bb1-37145c418d95 of type vlan for network 22c8b610-33e2-4910-b8a3-5f0e88dca049
2015-03-10 03:15:31.136 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.136 27055 ERROR neutron.api.v2.resource [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] create failed
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.138 27055 INFO neutron.wsgi [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.204934
2015-03-10 03:15:31.164 27056 INFO neutron.plugins.ml2.db [req-88bb3b71-e55a-4a8a-b5c5-3af74b712f1e None] Added segment 66bb4ba6-b7ec-4319-ad01-3f8873bb83f9 of type vlan for network 0af048d0-7ff4-4a3c-8ef3-a06bfeb886a2
2015-03-09 03:15:18.908 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40889)
2015-03-09 03:15:18.910 15289 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 03:15:18.982 15289 INFO neutron.plugins.ml2.managers [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:18.984 15289 INFO neutron.wsgi [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] 13.0.0.3 - - [09/Mar/2015 03:15:18] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=bddb85f8-150a-4252-84c9-05b2918899c5 HTTP/1.1" 200 996 0.074996
2015-03-09 03:15:18.987 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40895)
2015-03-09 03:15:18.997 15289 INFO neutron.plugins.ml2.managers [req-8d47e404-7957-4839-9c72-a340d61ce569 None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.000 15289 INFO neutron.wsgi [req-8d47e404-7957-4839-9c72-a340d61ce569 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/networks.json?id=619b3cb6-c5bb-469b-8525-44a53fc87630 HTTP/1.1" 200 578 0.012433
2015-03-09 03:15:19.002 15303 INFO neutron.wsgi [-] (15303) accepted ('13.0.0.3', 40896)
2015-03-09 03:15:19.009 15303 INFO neutron.wsgi [req-a6f0586e-a8fb-4c11-a149-c5555b85b384 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.9.2&port_id=ce179fb2-6014-4f8e-acaa-6a1dd23d8887 HTTP/1.1" 200 208 0.005573
2015-03-09 03:15:19.011 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40897)
2015-03-09 03:15:19.021 15289 INFO neutron.plugins.ml2.managers [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.021 15289 INFO neutron.wsgi [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/subnets.json?id=cf17974a-345d-40f1-8fa6-87fff881e1fe HTTP/1.1" 200 623 0.009591
2015-03-09 03:15:19.024 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40898)
2015-03-09 03:15:19.041 15289 INFO neutron.plugins.ml2.managers [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.042 15289 INFO neutron.wsgi [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/ports.json?network_id=619b3cb6-c5bb-469b-8525-44a53fc87630&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.017388
2015-03-09 03:15:38.698 15273 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:54.176 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41490)
2015-03-09 03:15:54.194 15289 INFO neutron.plugins.ml2.managers [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.196 15289 INFO neutron.wsgi [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=8bc3989e-8836-4cdb-8fff-0ce279933da4 HTTP/1.1" 200 996 0.018769
2015-03-09 03:15:54.198 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41491)
2015-03-09 03:15:54.210 15289 INFO neutron.plugins.ml2.managers [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.213 15289 INFO neutron.wsgi [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/networks.json?id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4 HTTP/1.1" 200 577 0.014159
2015-03-09 03:15:54.215 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41492)
2015-03-09 03:15:54.220 15289 INFO neutron.wsgi [req-b0221032-e7d4-45e7-894f-54e8b3bd75db None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.2.2&port_id=8640b9eb-affb-47ce-84fb-32c2d4ce1baf HTTP/1.1" 200 208 0.004424
2015-03-09 03:15:54.222 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41493)
2015-03-09 03:15:54.233 15289 INFO neutron.plugins.ml2.managers [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.234 15289 INFO neutron.wsgi [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/subnets.json?id=1e6eeaf3-d276-4384-b6d7-73c2f65446b5 HTTP/1.1" 200 622 0.010641
2015-03-09 03:15:54.236 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41494)
2015-03-09 03:15:54.252 15289 INFO neutron.plugins.ml2.managers [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.253 15289 INFO neutron.wsgi [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?network_id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.016796
2015-03-10 03:15:30.584 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57238)
2015-03-10 03:15:30.588 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.664 27053 INFO neutron.wsgi [-] (27053) accepted ('13.0.0.3', 57248)
2015-03-10 03:15:30.669 27053 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.702 27057 INFO neutron.wsgi [-] (27057) accepted ('13.0.0.3', 57254)
2015-03-10 03:15:30.708 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.709 27060 INFO neutron.wsgi [-] (27060) accepted ('13.0.0.3', 57257)
2015-03-10 03:15:30.713 27060 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.751 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57266)
2015-03-10 03:15:30.756 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.759 27058 INFO keystonemiddleware.auth_token [-] Auth Token confirmed use of v3.0 apis
2015-03-10 03:15:30.768 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57270)
2015-03-10 03:15:30.773 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.777 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57274)
2015-03-10 03:15:30.779 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.892 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.901 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.910 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.912 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.919 27059 INFO neutron.wsgi [-] (27059) accepted ('13.0.0.3', 57286)
2015-03-10 03:15:30.924 27049 INFO neutron.wsgi [-] (27049) accepted ('13.0.0.3', 57288)
2015-03-10 03:15:30.929 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.933 27055 INFO neutron.wsgi [-] (27055) accepted ('13.0.0.3', 57290)
2015-03-10 03:15:30.947 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.958 27058 INFO neutron.quota [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4566a90>.
2015-03-10 03:15:30.967 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.969 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.976 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.978 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.994 27058 INFO neutron.plugins.ml2.db [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Added segment 01ae8df2-465b-4d54-9920-fa41a8caa930 of type vlan for network 64063da1-4a72-4609-85e7-1e942922c85f
2015-03-10 03:15:31.009 27053 INFO neutron.quota [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dce10>.
2015-03-10 03:15:31.015 27057 INFO neutron.quota [req-12862fe0-0f87-4024-8541-8875a015e943 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.017 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.018 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.019 27060 INFO neutron.quota [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.021 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.026 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.030 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.036 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.037 27057 INFO neutron.plugins.ml2.db [req-12862fe0-0f87-4024-8541-8875a015e943 None] Added segment 5df1e09c-afda-49ed-aed6-765789e0bf02 of type vlan for network 66dc694d-83c5-4c10-a688-7b317876407e
2015-03-10 03:15:31.048 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.048 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.063 27053 ERROR neutron.api.v2.resource [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] create failed
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.065 27049 INFO neutron.quota [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41dfe50>.
2015-03-10 03:15:31.066 27053 INFO neutron.wsgi [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401648
2015-03-10 03:15:31.068 27059 INFO neutron.quota [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.075 27055 INFO neutron.quota [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.086 27049 INFO neutron.plugins.ml2.db [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Added segment bbd59b56-df3e-4e2c-88ce-c03bf0e95222 of type vlan for network 8673537a-360e-4fb6-8af7-3b8c1a46f33a
2015-03-10 03:15:31.088 27058 ERROR neutron.api.v2.resource [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] create failed
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.091 27058 INFO neutron.wsgi [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.339519
2015-03-10 03:15:31.097 27049 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.099 27056 INFO neutron.quota [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x46f9a90>.
2015-03-10 03:15:31.109 27060 ERROR neutron.api.v2.resource [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] create failed
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.111 27060 INFO neutron.wsgi [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401427
2015-03-10 03:15:31.113 27059 ERROR neutron.api.v2.resource [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] create failed
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.115 27059 INFO neutron.wsgi [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.195798
2015-03-10 03:15:31.124 27056 INFO neutron.plugins.ml2.db [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Added segment d6c88af2-d06c-444a-9bb1-37145c418d95 of type vlan for network 22c8b610-33e2-4910-b8a3-5f0e88dca049
2015-03-10 03:15:31.136 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.136 27055 ERROR neutron.api.v2.resource [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] create failed
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.138 27055 INFO neutron.wsgi [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.204934
2015-03-10 03:15:31.164 27056 INFO neutron.plugins.ml2.db [req-88bb3b71-e55a-4a8a-b5c5-3af74b712f1e None] Added segment 66bb4ba6-b7ec-4319-ad01-3f8873bb83f9 of type vlan for network 0af048d0-7ff4-4a3c-8ef3-a06bfeb886a2
2015-03-10 03:15:31.176 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:18.908 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40889)
2015-03-09 03:15:18.910 15289 INFO urllib3.connectionpool [-] Resetting dropped connection: 13.0.0.25
2015-03-09 03:15:18.982 15289 INFO neutron.plugins.ml2.managers [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:18.984 15289 INFO neutron.wsgi [req-9ccca7fa-e678-435b-9559-555a63d3c565 None] 13.0.0.3 - - [09/Mar/2015 03:15:18] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=bddb85f8-150a-4252-84c9-05b2918899c5 HTTP/1.1" 200 996 0.074996
2015-03-09 03:15:18.987 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40895)
2015-03-09 03:15:18.997 15289 INFO neutron.plugins.ml2.managers [req-8d47e404-7957-4839-9c72-a340d61ce569 None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.000 15289 INFO neutron.wsgi [req-8d47e404-7957-4839-9c72-a340d61ce569 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/networks.json?id=619b3cb6-c5bb-469b-8525-44a53fc87630 HTTP/1.1" 200 578 0.012433
2015-03-09 03:15:19.002 15303 INFO neutron.wsgi [-] (15303) accepted ('13.0.0.3', 40896)
2015-03-09 03:15:19.009 15303 INFO neutron.wsgi [req-a6f0586e-a8fb-4c11-a149-c5555b85b384 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.9.2&port_id=ce179fb2-6014-4f8e-acaa-6a1dd23d8887 HTTP/1.1" 200 208 0.005573
2015-03-09 03:15:19.011 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40897)
2015-03-09 03:15:19.021 15289 INFO neutron.plugins.ml2.managers [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.021 15289 INFO neutron.wsgi [req-678c4192-dc2d-4cc1-8d84-96a213c1c41b None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/subnets.json?id=cf17974a-345d-40f1-8fa6-87fff881e1fe HTTP/1.1" 200 623 0.009591
2015-03-09 03:15:19.024 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 40898)
2015-03-09 03:15:19.041 15289 INFO neutron.plugins.ml2.managers [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:19.042 15289 INFO neutron.wsgi [req-5c5e74c3-d456-4b53-b4e2-e31bec7c9b06 None] 13.0.0.3 - - [09/Mar/2015 03:15:19] "GET /v2.0/ports.json?network_id=619b3cb6-c5bb-469b-8525-44a53fc87630&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.017388
2015-03-09 03:15:38.698 15273 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-09 03:15:54.176 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41490)
2015-03-09 03:15:54.194 15289 INFO neutron.plugins.ml2.managers [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.196 15289 INFO neutron.wsgi [req-05508716-6bab-48a8-860c-3ebcf28a6387 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?tenant_id=cd8e05c53c6f4db79368f04564dcb4d3&device_id=8bc3989e-8836-4cdb-8fff-0ce279933da4 HTTP/1.1" 200 996 0.018769
2015-03-09 03:15:54.198 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41491)
2015-03-09 03:15:54.210 15289 INFO neutron.plugins.ml2.managers [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] Extended network dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.213 15289 INFO neutron.wsgi [req-1aa8039d-a0c1-435c-b877-1a64e5ec7bfa None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/networks.json?id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4 HTTP/1.1" 200 577 0.014159
2015-03-09 03:15:54.215 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41492)
2015-03-09 03:15:54.220 15289 INFO neutron.wsgi [req-b0221032-e7d4-45e7-894f-54e8b3bd75db None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/floatingips.json?fixed_ip_address=14.6.2.2&port_id=8640b9eb-affb-47ce-84fb-32c2d4ce1baf HTTP/1.1" 200 208 0.004424
2015-03-09 03:15:54.222 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41493)
2015-03-09 03:15:54.233 15289 INFO neutron.plugins.ml2.managers [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] Extended subnet dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.234 15289 INFO neutron.wsgi [req-803acf5e-0fcb-43f7-a7d7-09d878511c88 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/subnets.json?id=1e6eeaf3-d276-4384-b6d7-73c2f65446b5 HTTP/1.1" 200 622 0.010641
2015-03-09 03:15:54.236 15289 INFO neutron.wsgi [-] (15289) accepted ('13.0.0.3', 41494)
2015-03-09 03:15:54.252 15289 INFO neutron.plugins.ml2.managers [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] Extended port dict for driver 'cisco_n1kv_ext'
2015-03-09 03:15:54.253 15289 INFO neutron.wsgi [req-e7617def-b020-424e-86a2-bd1f5ad40be7 None] 13.0.0.3 - - [09/Mar/2015 03:15:54] "GET /v2.0/ports.json?network_id=e8ebc4db-8b64-4c4e-96b9-f9f6668767d4&device_owner=network%3Adhcp HTTP/1.1" 200 983 0.016796
2015-03-10 03:15:30.584 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57238)
2015-03-10 03:15:30.588 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.664 27053 INFO neutron.wsgi [-] (27053) accepted ('13.0.0.3', 57248)
2015-03-10 03:15:30.669 27053 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.702 27057 INFO neutron.wsgi [-] (27057) accepted ('13.0.0.3', 57254)
2015-03-10 03:15:30.708 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.709 27060 INFO neutron.wsgi [-] (27060) accepted ('13.0.0.3', 57257)
2015-03-10 03:15:30.713 27060 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.751 27058 INFO neutron.wsgi [-] (27058) accepted ('13.0.0.3', 57266)
2015-03-10 03:15:30.756 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.759 27058 INFO keystonemiddleware.auth_token [-] Auth Token confirmed use of v3.0 apis
2015-03-10 03:15:30.768 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57270)
2015-03-10 03:15:30.773 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.25
2015-03-10 03:15:30.777 27056 INFO neutron.wsgi [-] (27056) accepted ('13.0.0.3', 57274)
2015-03-10 03:15:30.779 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (2): 13.0.0.25
2015-03-10 03:15:30.892 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.901 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.910 27058 INFO oslo.messaging._drivers.impl_rabbit [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.912 27058 INFO oslo.messaging._drivers.impl_rabbit [req-2a03b433-00ed-4083-b8c7-935d25cc96ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.919 27059 INFO neutron.wsgi [-] (27059) accepted ('13.0.0.3', 57286)
2015-03-10 03:15:30.924 27049 INFO neutron.wsgi [-] (27049) accepted ('13.0.0.3', 57288)
2015-03-10 03:15:30.929 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.933 27055 INFO neutron.wsgi [-] (27055) accepted ('13.0.0.3', 57290)
2015-03-10 03:15:30.947 27053 INFO oslo.messaging._drivers.impl_rabbit [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.958 27058 INFO neutron.quota [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x4566a90>.
2015-03-10 03:15:30.967 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.969 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.976 27057 INFO oslo.messaging._drivers.impl_rabbit [req-12862fe0-0f87-4024-8541-8875a015e943 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.978 27060 INFO oslo.messaging._drivers.impl_rabbit [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:30.994 27058 INFO neutron.plugins.ml2.db [req-41aa20b3-80d1-48a7-b3c1-d06c9fac9eae None] Added segment 01ae8df2-465b-4d54-9920-fa41a8caa930 of type vlan for network 64063da1-4a72-4609-85e7-1e942922c85f
2015-03-10 03:15:31.009 27053 INFO neutron.quota [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dce10>.
2015-03-10 03:15:31.015 27057 INFO neutron.quota [req-12862fe0-0f87-4024-8541-8875a015e943 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.017 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.018 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.019 27060 INFO neutron.quota [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x45dde10>.
2015-03-10 03:15:31.021 27058 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.026 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27049 INFO oslo.messaging._drivers.impl_rabbit [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.027 27059 INFO oslo.messaging._drivers.impl_rabbit [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.030 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connecting to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.036 27055 INFO oslo.messaging._drivers.impl_rabbit [req-40d11020-a7ad-4262-8d58-d1c5872474ea ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.037 27057 INFO neutron.plugins.ml2.db [req-12862fe0-0f87-4024-8541-8875a015e943 None] Added segment 5df1e09c-afda-49ed-aed6-765789e0bf02 of type vlan for network 66dc694d-83c5-4c10-a688-7b317876407e
2015-03-10 03:15:31.048 27057 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.048 27056 INFO oslo.messaging._drivers.impl_rabbit [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 ] Connected to AMQP server on 13.0.0.3:5672
2015-03-10 03:15:31.063 27053 ERROR neutron.api.v2.resource [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] create failed
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.063 27053 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.065 27049 INFO neutron.quota [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41dfe50>.
2015-03-10 03:15:31.066 27053 INFO neutron.wsgi [req-be1060fd-5c22-4dae-bb25-99c87f5e91fe None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401648
2015-03-10 03:15:31.068 27059 INFO neutron.quota [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.075 27055 INFO neutron.quota [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x41de890>.
2015-03-10 03:15:31.086 27049 INFO neutron.plugins.ml2.db [req-926781ae-b7cc-4b0b-a86c-a30d88e2287a None] Added segment bbd59b56-df3e-4e2c-88ce-c03bf0e95222 of type vlan for network 8673537a-360e-4fb6-8af7-3b8c1a46f33a
2015-03-10 03:15:31.088 27058 ERROR neutron.api.v2.resource [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] create failed
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.088 27058 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.091 27058 INFO neutron.wsgi [req-2a03b433-00ed-4083-b8c7-935d25cc96ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.339519
2015-03-10 03:15:31.097 27049 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.099 27056 INFO neutron.quota [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Loaded quota_driver: <neutron.db.quota_db.DbQuotaDriver object at 0x46f9a90>.
2015-03-10 03:15:31.109 27060 ERROR neutron.api.v2.resource [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] create failed
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.109 27060 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.111 27060 INFO neutron.wsgi [req-4f4a3c7f-5d29-4694-a3d8-bc2af14f7ab9 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.401427
2015-03-10 03:15:31.113 27059 ERROR neutron.api.v2.resource [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] create failed
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.113 27059 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.115 27059 INFO neutron.wsgi [req-d5cbeb4c-9465-4f96-b0bf-16f8a51dd716 None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.195798
2015-03-10 03:15:31.124 27056 INFO neutron.plugins.ml2.db [req-e66f3c73-43c2-4333-ac68-4ba2b713e4d4 None] Added segment d6c88af2-d06c-444a-9bb1-37145c418d95 of type vlan for network 22c8b610-33e2-4910-b8a3-5f0e88dca049
2015-03-10 03:15:31.136 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
2015-03-10 03:15:31.136 27055 ERROR neutron.api.v2.resource [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] create failed
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 448, in create
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 499, in create_network
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     tenant_id)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 160, in create_network_segments
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = self.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/managers.py", line 189, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     segment = driver.obj.allocate_tenant_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/type_vlan.py", line 220, in allocate_tenant_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     alloc = self.allocate_partially_specified_segment(session)
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/helpers.py", line 143, in allocate_partially_specified_segment
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource     raise exc.NoNetworkFoundInMaximumAllowedAttempts()
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource NoNetworkFoundInMaximumAllowedAttempts: Unable to create the network. No available network found in maximum allowed attempts.
2015-03-10 03:15:31.136 27055 TRACE neutron.api.v2.resource 
2015-03-10 03:15:31.138 27055 INFO neutron.wsgi [req-40d11020-a7ad-4262-8d58-d1c5872474ea None] 13.0.0.3 - - [10/Mar/2015 03:15:31] "POST /v2.0/networks.json HTTP/1.1" 503 389 0.204934
2015-03-10 03:15:31.164 27056 INFO neutron.plugins.ml2.db [req-88bb3b71-e55a-4a8a-b5c5-3af74b712f1e None] Added segment 66bb4ba6-b7ec-4319-ad01-3f8873bb83f9 of type vlan for network 0af048d0-7ff4-4a3c-8ef3-a06bfeb886a2
2015-03-10 03:15:31.176 27056 INFO urllib3.connectionpool [-] Starting new HTTP connection (1): 13.0.0.250
